# Generated by Django 6.0.5 on 2026-05-26 22:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_clientesmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prato', models.CharField(max_length=1000)),
                ('detalhes_pedido', models.CharField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('cliente_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel')),
            ],
        ),
    ]
