# Generated by Django 6.0.5 on 2026-05-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapiomodel',
            name='status_pedido',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
