# Generated by Django 6.0.5 on 2026-05-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_cardapiomodel_status_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiomodel',
            name='status_pedido',
            field=models.CharField(max_length=30),
        ),
    ]
