# Generated by Django 6.0.5 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_cardapiomodel_status_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiomodel',
            name='valor',
            field=models.CharField(max_length=1000000000000),
        ),
    ]
