# Generated by Django 6.0.5 on 2026-05-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_cardapiomodel_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapiomodel',
            name='cliente_cardapio',
        ),
        migrations.RemoveField(
            model_name='cardapiomodel',
            name='status_pedido',
        ),
    ]
