# Generated by Django 6.0.5 on 2026-06-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cardapiomodel_cliente_cardapio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapiomodel',
            name='tamanho_pedido',
            field=models.CharField(choices=[('PEQUENO', 'BASICA'), ('MEDIO', 'INTERMEDIARIO'), ('GRANDE', 'ENORME')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardapiomodel',
            name='detalhes_pedido',
            field=models.CharField(max_length=1000000000000),
        ),
    ]
