# Generated by Django 6.0.5 on 2026-06-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0006_cardapiomodel_tamanho_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapiomodel',
            old_name='detalhes_pedido',
            new_name='detalhes_prato',
        ),
        migrations.RenameField(
            model_name='cardapiomodel',
            old_name='tamanho_pedido',
            new_name='tamanho_prato',
        ),
    ]
