# Generated by Django 6.0.5 on 2026-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_rename_detalhes_pedido_cardapiomodel_detalhes_prato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapiomodel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
