# Generated by Django 6.0.5 on 2026-06-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0018_remove_pedidomodel_metodo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('DEBITO', 'DEBITO'), ('DINHEIRO', 'DINHEIRO')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedidomodel')),
            ],
        ),
    ]
