# Generated by Django 6.0.5 on 2026-06-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        ('pedidos', '0019_pedidomodel_pagamento_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='pedido',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='pedido',
            field=models.ManyToManyField(related_name='pedidos', to='pedidos.pedidomodel'),
        ),
    ]
