# Generated by Django 6.0.5 on 2026-06-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_remove_paymentmodel_pedido_paymentmodel_pedido'),
        ('pedidos', '0019_pedidomodel_pagamento_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='pedido',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='pedido',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedidomodel'),
            preserve_default=False,
        ),
    ]
