# Generated by Django 6.0.5 on 2026-05-29 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0004_alter_cardapiomodel_valor'),
        ('clientes', '0003_alter_clientesmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapiomodel')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_lanche', models.CharField(choices=[('PEQUENO', 'BASICA'), ('MEDIO', 'INTERMEDIARIO'), ('GRANDE', 'ENORME')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel')),
                ('prato_cliente', models.ManyToManyField(related_name='pedidos', through='pedidos.ItemPedidoModel', to='cardapio.cardapiomodel')),
            ],
        ),
        migrations.AddField(
            model_name='itempedidomodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
    ]
