# Generated by Django 6.0.5 on 2026-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cardapiomodel_cliente_cardapio_and_more'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='status_pedido',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='prato_cliente',
            field=models.ManyToManyField(related_name='cardapio', through='pedidos.ItemPedidoModel', to='cardapio.cardapiomodel'),
        ),
    ]
