# Generated by Django 6.0.5 on 2026-06-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cardapiomodel_cliente_cardapio_and_more'),
        ('pedidos', '0002_pedidomodel_status_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidomodel',
            name='prato',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='prato_cliente',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='prato_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapiomodel'),
            preserve_default=False,
        ),
    ]
