# Generated by Django 6.0.5 on 2026-06-04 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cardapiomodel_cliente_cardapio_and_more'),
        ('clientes', '0003_alter_clientesmodel_id'),
        ('pedidos', '0003_remove_itempedidomodel_prato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedidomodel',
            old_name='quantidade',
            new_name='quantidade_kg',
        ),
        migrations.AddField(
            model_name='itempedidomodel',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedidomodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapiomodel'),
        ),
    ]
