# Generated by Django 6.0.5 on 2026-06-06 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_remove_cardapiomodel_cliente_cardapio_and_more'),
        ('clientes', '0003_alter_clientesmodel_id'),
        ('pedidos', '0004_rename_quantidade_itempedidomodel_quantidade_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidomodel',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='pedido_cliente',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='prato_cliente',
        ),
        migrations.AddField(
            model_name='itempedidomodel',
            name='prato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapiomodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='pedido',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.clientesmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='prato',
            field=models.ManyToManyField(through='pedidos.ItemPedidoModel', to='cardapio.cardapiomodel'),
        ),
        migrations.AlterField(
            model_name='itempedidomodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidomodel'),
        ),
    ]
