# Generated by Django 6.0.5 on 2026-06-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_itempedidomodel_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='pedido',
            new_name='pedido_cliente',
        ),
        migrations.RenameField(
            model_name='pedidomodel',
            old_name='prato',
            new_name='prato_cliente',
        ),
    ]
