# Generated by Django 6.0.5 on 2026-06-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_pedido_pedidomodel_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomodel',
            name='tamanho_lanche',
            field=models.CharField(max_length=20),
        ),
    ]
