# Generated by Django 6.0.5 on 2026-06-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedidomodel_tamanho_lanche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='tamanho_lanche',
        ),
    ]
