# Generated by Django 6.0.5 on 2026-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedidomodel_tamanho_lanche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidomodel',
            name='quantidade_kg',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='quantidade_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='quantidade_pedido',
            field=models.IntegerField(default=1),
        ),
    ]
