# Generated by Django 6.0.5 on 2026-06-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientesmodel_id'),
        ('pedidos', '0009_remove_itempedidomodel_quantidade_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidomodel',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel'),
            preserve_default=False,
        ),
    ]
