# Generated by Django 6.0.5 on 2026-06-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_rename_detalhes_pedido_cardapiomodel_detalhes_prato_and_more'),
        ('pedidos', '0010_itempedidomodel_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='prato_cliente',
        ),
        migrations.AddField(
            model_name='pedidomodel',
            name='prato_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cardapio.cardapiomodel'),
            preserve_default=False,
        ),
    ]
