# Generated by Django 6.0.5 on 2026-06-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_remove_pedidomodel_prato_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPedidoModel',
        ),
    ]
