# Generated by Django 6.0.5 on 2026-06-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_rename_detalhes_pedido_cardapiomodel_detalhes_prato_and_more'),
        ('pedidos', '0012_delete_itempedidomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapiomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidomodel')),
            ],
        ),
    ]
