# Generated by Django 6.0.5 on 2026-06-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientesmodel_id'),
        ('pedidos', '0014_itempedidomodel_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedidomodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientesmodel'),
        ),
    ]
