# Generated by Django 6.0.5 on 2026-06-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_itempedidomodel_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedidomodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemPedidoModel',
        ),
    ]
