# Generated by Django 6.0.5 on 2026-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_itempedido_pedido_delete_itempedidomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CARTAO DE CREDITO', 'CARTAO DE CREDITO'), ('DEBITO', 'DEBITO'), ('DINHEIRO', 'DINHEIRO')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
