# Generated by Django 6.0.5 on 2026-06-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pedidomodel_metodo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='metodo_pagamento',
        ),
    ]
