# Generated by Django 6.0.5 on 2026-06-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientesmodel_id'),
        ('pagamentos', '0001_initial'),
        ('pedidos', '0018_remove_pedidomodel_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomodel',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='pagamentos.paymentmodel'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clientes.clientesmodel'),
        ),
    ]
