# Generated by Django 6.0.5 on 2026-06-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_remove_paymentmodel_pedido_paymentmodel_pedido'),
        ('pedidos', '0020_alter_pedidomodel_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamentos.paymentmodel'),
        ),
    ]
