# Generated by Django 6.0.5 on 2026-06-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0022_alter_itempedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='prato_cliente',
        ),
    ]
