# Generated by Django 6.0.5 on 2026-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_remove_pedidomodel_prato_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidomodel',
            name='quantidade_kg',
        ),
        migrations.RemoveField(
            model_name='pedidomodel',
            name='quantidade_pedido',
        ),
        migrations.AlterField(
            model_name='pedidomodel',
            name='status_pedido',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto'), ('SAIU_PARA_ENTREGA', 'Saiu para Entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=20),
        ),
    ]
