# Generated by Django 6.0.5 on 2026-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
