# Generated by Django 6.0.5 on 2026-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientesmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
